# Generated by autonix
# Rust build checks
{ pkgs, lib, devPackages, projectRoot }:

{
  "rust-build-cargo-build-cargo-toml" = let
    cmd = "cargo build";
    requiredExec = "cargo";
    workdir = ".";
    display = "cargo build";
  in pkgs.runCommand "check-rust-build-cargo-build-cargo-toml" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "rust-build-cargo-build-release-cargo-toml" = let
    cmd = "cargo build --release";
    requiredExec = "cargo";
    workdir = ".";
    display = "cargo build --release";
  in pkgs.runCommand "check-rust-build-cargo-build-release-cargo-toml" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

}
