# Generated by autonix
# Rust toolchain and development tools
{ pkgs, lib }:

let
  rustToolchainBase = pkgs.rust-bin.stable.latest.default;

  rustToolchain = rustToolchainBase.override {
    extensions = [ "rust-src" "rust-analyzer" ];
  };

  notices = [];
in
{
  inherit rustToolchain notices;

  packages = [ rustToolchain ];
}
