# Generated by autonix
# Rust test checks
{ pkgs, lib, devPackages, projectRoot }:

{
  "rust-test-cargo-test-cargo-toml" = let
    cmd = "cargo test";
    requiredExec = "cargo";
    workdir = ".";
    display = "cargo test";
  in pkgs.runCommand "check-rust-test-cargo-test-cargo-toml" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

}
