{
  description = "Generated by autonix (devShells.default + checks)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        lib = pkgs.lib;

        wantNodeAttr = "nodejs_0";
        nodeAttr = if builtins.hasAttr wantNodeAttr pkgs then wantNodeAttr else "nodejs";
        node = pkgs.${nodeAttr};


        devPackages =
          [
            node
            pkgs.nodePackages.typescript
            pkgs.nodePackages.typescript-language-server
          ];

      in
      {
        devShells.default = pkgs.mkShell {
          packages = devPackages;
          shellHook = ''
            echo "autonix: generated devShell (best-effort)"
            echo "autonix: Node attr: ${nodeAttr} (requested ${wantNodeAttr})"
            if [ "${nodeAttr}" != "${wantNodeAttr}" ]; then
              echo "autonix: NOTE: ${wantNodeAttr} not found; using ${nodeAttr}"
            fi
            echo ${lib.escapeShellArg "Node: requested >= 0.10.0 (from PackageJsonEnginesNode) -> want nodejs_0 note: nixpkgs provides Node.js by major (minor/patch may differ)"}
          '';
        };

        checks = {
          "test-npmscripts-test-ci-package-json" = let
            cmd = "npm run test-ci";
            requiredExec = "npm";
            workdir = "";
            display = "npm run test-ci  # nyc --exclude examples --exclude test --exclude benchmarks --reporter=lcovonly --reporter=text npm test";
          in pkgs.runCommand "check-test-npmscripts-test-ci-package-json" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-npmscripts-test-cov-package-json" = let
            cmd = "npm run test-cov";
            requiredExec = "npm";
            workdir = "";
            display = "npm run test-cov  # nyc --exclude examples --exclude test --exclude benchmarks --reporter=html --reporter=text npm test";
          in pkgs.runCommand "check-test-npmscripts-test-cov-package-json" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-npmscripts-test-package-json" = let
            cmd = "npm run test";
            requiredExec = "npm";
            workdir = "";
            display = "npm run test  # mocha --require test/support/env --reporter spec --bail --check-leaks test/ test/acceptance/";
          in pkgs.runCommand "check-test-npmscripts-test-package-json" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-npmscripts-test-tap-package-json" = let
            cmd = "npm run test-tap";
            requiredExec = "npm";
            workdir = "";
            display = "npm run test-tap  # mocha --require test/support/env --reporter tap --check-leaks test/ test/acceptance/";
          in pkgs.runCommand "check-test-npmscripts-test-tap-package-json" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
        };
      });
}
