# Generated by autonix
#
# This flake uses a multi-file structure:
#   .autonix/devShell.nix              - Development shell
#   .autonix/{language}/packages.nix   - Language toolchains and tools
#   .autonix/{language}/*-checks.nix   - Build and test checks
#
{
  description = "Generated by autonix (devShells.default + checks)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        lib = pkgs.lib;

        pythonPackages = import .autonix/python/packages.nix { inherit pkgs lib; };

        devPackages = []
          ++ pythonPackages.packages;

        notices = []
          ++ pythonPackages.notices;

        projectRoot = ./.;

      in
      {
        devShells.default = import .autonix/devShell.nix {
          inherit pkgs lib devPackages notices;
          python = pythonPackages.python or null;
          pythonAttr = pythonPackages.pythonAttr or null;
          wantPythonAttr = pythonPackages.wantPythonAttr or null;
        };

        checks = {}
          // (import .autonix/python/test-checks.nix { inherit pkgs lib devPackages projectRoot; })
          ;
      });
}
