{
  description = "Generated by autonix (devShells.default + checks)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }: 
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        lib = pkgs.lib;

        wantPythonAttr = "python39";
        pythonAttr = if builtins.hasAttr wantPythonAttr pkgs then wantPythonAttr else "python3";
        python = pkgs.${pythonAttr};
        wantPythonPackagesAttr = "${pythonAttr}Packages";
        pythonPackages = if builtins.hasAttr wantPythonPackagesAttr pkgs then pkgs.${wantPythonPackagesAttr} else pkgs.python3Packages;

        tox = if builtins.hasAttr "tox" pythonPackages then pythonPackages.tox else null;
        pyright = if builtins.hasAttr "pyright" pkgs then pkgs.pyright
          else if builtins.hasAttr "pyright" pkgs.nodePackages then pkgs.nodePackages.pyright
          else null;

        devPackages =
          [
            python
          ]
          ++ lib.optional (tox != null) tox
          ++ lib.optional (pyright != null) pyright;

      in
      {
        devShells.default = pkgs.mkShell {
          packages = devPackages;
          shellHook = ''
            echo "autonix: generated devShell (best-effort)"
            echo "autonix: Python attr: ${pythonAttr} (requested ${wantPythonAttr})"
            if [ "${pythonAttr}" != "${wantPythonAttr}" ]; then
              echo "autonix: NOTE: ${wantPythonAttr} not found; using ${pythonAttr}"
            fi
            echo ${lib.escapeShellArg "Python: requested >=3.9 (from PyprojectRequiresPython) -> want python39 note: nixpkgs provides Python by major/minor (patch may differ)"}
          '';
        };

        checks = {
          "test-tox-default-tox-ini" = let
            cmd = "tox";
            requiredExec = "tox";
            workdir = ".";
            display = "tox";
          in pkgs.runCommand "check-test-tox-default-tox-ini" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
        };
      });
}
