{
  description = "Generated by autonix (devShells.default + checks)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, rust-overlay }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [ (import rust-overlay) ];
        pkgs = import nixpkgs { inherit system overlays; };
        lib = pkgs.lib;

        rustToolchainBase = pkgs.rust-bin.stable.latest.default;
        rustToolchain = rustToolchainBase.override {
          extensions = [ "rust-src" "rust-analyzer" ];
        };

        devPackages =
          [
            rustToolchain
          ];

      in
      {
        devShells.default = pkgs.mkShell {
          packages = devPackages;
          shellHook = ''
            echo "autonix: generated devShell (best-effort)"
            echo "autonix: Rust toolchain enabled (rust-overlay)"
          '';
        };

        checks = {
          "build-cargo-build-cargo-toml" = let
            cmd = "cargo build";
            requiredExec = "cargo";
            workdir = ".";
            display = "cargo build";
          in pkgs.runCommand "check-build-cargo-build-cargo-toml" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-cargo-build-release-cargo-toml" = let
            cmd = "cargo build --release";
            requiredExec = "cargo";
            workdir = ".";
            display = "cargo build --release";
          in pkgs.runCommand "check-build-cargo-build-release-cargo-toml" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-cargo-test-cargo-toml" = let
            cmd = "cargo test";
            requiredExec = "cargo";
            workdir = ".";
            display = "cargo test";
          in pkgs.runCommand "check-test-cargo-test-cargo-toml" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
        };
      });
}
