{
  description = "Generated by autonix (devShells.default + checks)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }: 
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        lib = pkgs.lib;

        wantGoAttr = "go_1_23";
        goAttr = if builtins.hasAttr wantGoAttr pkgs then wantGoAttr else "go";
        go = pkgs.${goAttr};

        devPackages =
          [
            go
            pkgs.gopls
            pkgs.gnumake
          ];

      in
      {
        devShells.default = pkgs.mkShell {
          packages = devPackages;
          shellHook = ''
            echo "autonix: generated devShell (best-effort)"
            echo "autonix: Go attr: ${goAttr} (requested ${wantGoAttr})"
            if [ "${goAttr}" != "${wantGoAttr}" ]; then
              echo "autonix: NOTE: ${wantGoAttr} not found; using ${goAttr}"
            fi
            echo ${lib.escapeShellArg "Go: requested 1.23.0 (from GoModDirective) -> want go_1_23 note: nixpkgs provides Go by major/minor (patch may differ)"}
          '';
        };

        checks = {
          "build-gotask-build-go-mod" = let
            cmd = "go build";
            requiredExec = "go";
            workdir = ".";
            display = "go build";
          in pkgs.runCommand "check-build-gotask-build-go-mod" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-make-build-image-dirty-makefile" = let
            cmd = "make build-image-dirty";
            requiredExec = "make";
            workdir = ".";
            display = "make build-image-dirty";
          in pkgs.runCommand "check-build-make-build-image-dirty-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-make-build-image-dirty-makefile-2" = let
            cmd = "make build-image-dirty";
            requiredExec = "make";
            workdir = ".";
            display = "make build-image-dirty";
          in pkgs.runCommand "check-build-make-build-image-dirty-makefile-2" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-make-build-image-dirty-makefile-3" = let
            cmd = "make build-image-dirty";
            requiredExec = "make";
            workdir = ".";
            display = "make build-image-dirty";
          in pkgs.runCommand "check-build-make-build-image-dirty-makefile-3" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-make-build-image-makefile" = let
            cmd = "make build-image";
            requiredExec = "make";
            workdir = ".";
            display = "make build-image";
          in pkgs.runCommand "check-build-make-build-image-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-make-build-image-makefile-2" = let
            cmd = "make build-image";
            requiredExec = "make";
            workdir = ".";
            display = "make build-image";
          in pkgs.runCommand "check-build-make-build-image-makefile-2" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-make-build-image-makefile-3" = let
            cmd = "make build-image";
            requiredExec = "make";
            workdir = ".";
            display = "make build-image";
          in pkgs.runCommand "check-build-make-build-image-makefile-3" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-make-build-webui-image-makefile" = let
            cmd = "make build-webui-image";
            requiredExec = "make";
            workdir = ".";
            display = "make build-webui-image";
          in pkgs.runCommand "check-build-make-build-webui-image-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-make-dist-makefile" = let
            cmd = "make dist";
            requiredExec = "make";
            workdir = ".";
            display = "make dist";
          in pkgs.runCommand "check-build-make-dist-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "build-make-release-packages-makefile" = let
            cmd = "make release-packages";
            requiredExec = "make";
            workdir = ".";
            display = "make release-packages";
          in pkgs.runCommand "check-build-make-release-packages-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-gotask-test-go-mod" = let
            cmd = "go test ./...";
            requiredExec = "go";
            workdir = ".";
            display = "go test ./...";
          in pkgs.runCommand "check-test-gotask-test-go-mod" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-make-test-gateway-api-conformance-makefile" = let
            cmd = "make test-gateway-api-conformance";
            requiredExec = "make";
            workdir = ".";
            display = "make test-gateway-api-conformance";
          in pkgs.runCommand "check-test-make-test-gateway-api-conformance-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-make-test-integration-makefile" = let
            cmd = "make test-integration";
            requiredExec = "make";
            workdir = ".";
            display = "make test-integration";
          in pkgs.runCommand "check-test-make-test-integration-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-make-test-makefile" = let
            cmd = "make test";
            requiredExec = "make";
            workdir = ".";
            display = "make test";
          in pkgs.runCommand "check-test-make-test-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-make-test-ui-unit-makefile" = let
            cmd = "make test-ui-unit";
            requiredExec = "make";
            workdir = ".";
            display = "make test-ui-unit";
          in pkgs.runCommand "check-test-make-test-ui-unit-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
          "test-make-test-unit-makefile" = let
            cmd = "make test-unit";
            requiredExec = "make";
            workdir = ".";
            display = "make test-unit";
          in pkgs.runCommand "check-test-make-test-unit-makefile" {
            nativeBuildInputs = devPackages;
          } ''
            set -euo pipefail
            export HOME="$TMPDIR/home"
            mkdir -p "$HOME"

            echo "autonix: running ${display}"
            if ! command -v "${requiredExec}" >/dev/null 2>&1; then
              echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
              exit 1
            fi

            cp -r ${./.} source
            chmod -R u+w source
            cd "source/${workdir}"

            ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

            mkdir -p $out
            echo ok > $out/result
          '';
        };
      });
}
