# Generated by autonix
# Node.js build checks
{ pkgs, lib, devPackages, projectRoot }:

{
  "nodejs-build-npmscripts-build-package-json" = let
    cmd = "bun run build";
    requiredExec = "bun";
    workdir = "";
    display = "bun run build  # bun run --shell bun remove-dist && bun ./build/build.ts && bun run copy:package.cjs.json";
  in pkgs.runCommand "check-nodejs-build-npmscripts-build-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-build-npmscripts-copy-package-cjs-json-package-json" = let
    cmd = "bun run copy:package.cjs.json";
    requiredExec = "bun";
    workdir = "";
    display = "bun run copy:package.cjs.json  # cp ./package.cjs.json ./dist/cjs/package.json && cp ./package.cjs.json ./dist/types/package.json";
  in pkgs.runCommand "check-nodejs-build-npmscripts-copy-package-cjs-json-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-build-npmscripts-postbuild-package-json" = let
    cmd = "bun run postbuild";
    requiredExec = "bun";
    workdir = "";
    display = "bun run postbuild  # publint";
  in pkgs.runCommand "check-nodejs-build-npmscripts-postbuild-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-build-npmscripts-remove-dist-package-json" = let
    cmd = "bun run remove-dist";
    requiredExec = "bun";
    workdir = "";
    display = "bun run remove-dist  # rm -rf dist";
  in pkgs.runCommand "check-nodejs-build-npmscripts-remove-dist-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

}
