# Generated by autonix
# Node.js toolchain and development tools
{ pkgs, lib }:

let
  wantNodeAttr = "nodejs_16";
  nodeAttr = if builtins.hasAttr wantNodeAttr pkgs then wantNodeAttr else "nodejs";
  node = pkgs.${nodeAttr};

  yarn = if builtins.hasAttr "yarn" pkgs then pkgs.yarn else null;
  bun = if builtins.hasAttr "bun" pkgs then pkgs.bun else null;

  notices = [
    "Node: requested >=16.9.0 (from PackageJsonEnginesNode) -> want nodejs_16 note: nixpkgs provides Node.js by major (minor/patch may differ)"
  ];
in
{
  inherit node nodeAttr wantNodeAttr notices;

  packages =
    [
      node
      pkgs.nodePackages.typescript
      pkgs.nodePackages.typescript-language-server
    ]
    ++ lib.optional (yarn != null) yarn
    ++ lib.optional (bun != null) bun;
}
