# Generated by autonix
# Node.js test checks
{ pkgs, lib, devPackages, projectRoot }:

{
  "nodejs-test-npmscripts-test-all-package-json" = let
    cmd = "bun run test:all";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test:all  # bun run test && bun test:deno && bun test:bun && bun test:fastly && bun test:node && bun test:workerd && bun test:lambda && bun test:lambda-edge";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-all-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-bun-package-json" = let
    cmd = "bun run test:bun";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test:bun  # bun test --jsx-import-source ../../src/jsx runtime-tests/bun/index.test.tsx";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-bun-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-deno-package-json" = let
    cmd = "bun run test:deno";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test:deno  # deno test --allow-read --allow-env --allow-write --allow-net -c runtime-tests/deno/deno.json runtime-tests/deno && deno test --no-lock -c runtime-tests/deno-jsx/deno.precompile.json runtime-tests/deno-jsx && deno test --no-lock -c runtime-tests/deno-jsx/deno.react-jsx.json runtime-tests/deno-jsx";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-deno-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-fastly-package-json" = let
    cmd = "bun run test:fastly";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test:fastly  # vitest --run --config ./runtime-tests/fastly/vitest.config.ts";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-fastly-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-lambda-edge-package-json" = let
    cmd = "bun run test:lambda-edge";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test:lambda-edge  # vitest --run --config ./runtime-tests/lambda-edge/vitest.config.ts";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-lambda-edge-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-lambda-package-json" = let
    cmd = "bun run test:lambda";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test:lambda  # vitest --run --config ./runtime-tests/lambda/vitest.config.ts";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-lambda-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-node-package-json" = let
    cmd = "bun run test:node";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test:node  # vitest --run --config ./runtime-tests/node/vitest.config.ts";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-node-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-package-json" = let
    cmd = "bun run test";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test  # tsc --noEmit && vitest --run && vitest -c .vitest.config/jsx-runtime-default.ts --run && vitest -c .vitest.config/jsx-runtime-dom.ts --run";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-watch-package-json" = let
    cmd = "bun run test:watch";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test:watch  # vitest --watch";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-watch-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-workerd-package-json" = let
    cmd = "bun run test:workerd";
    requiredExec = "bun";
    workdir = "";
    display = "bun run test:workerd  # vitest --run --config ./runtime-tests/workerd/vitest.config.ts";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-workerd-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

}
