# Generated by autonix
# Node.js toolchain and development tools
{ pkgs, lib }:

let
  wantNodeAttr = "nodejs_0";
  nodeAttr = if builtins.hasAttr wantNodeAttr pkgs then wantNodeAttr else "nodejs";
  node = pkgs.${nodeAttr};


  notices = [
    "Node: requested >= 0.10.0 (from PackageJsonEnginesNode) -> want nodejs_0 note: nixpkgs provides Node.js by major (minor/patch may differ)"
  ];
in
{
  inherit node nodeAttr wantNodeAttr notices;

  packages =
    [
      node
      pkgs.nodePackages.typescript
      pkgs.nodePackages.typescript-language-server
    ];
}
