# Generated by autonix
# Node.js test checks
{ pkgs, lib, devPackages, projectRoot }:

{
  "nodejs-test-npmscripts-test-ci-package-json" = let
    cmd = "npm run test-ci";
    requiredExec = "npm";
    workdir = "";
    display = "npm run test-ci  # nyc --exclude examples --exclude test --exclude benchmarks --reporter=lcovonly --reporter=text npm test";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-ci-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-cov-package-json" = let
    cmd = "npm run test-cov";
    requiredExec = "npm";
    workdir = "";
    display = "npm run test-cov  # nyc --exclude examples --exclude test --exclude benchmarks --reporter=html --reporter=text npm test";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-cov-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-package-json" = let
    cmd = "npm run test";
    requiredExec = "npm";
    workdir = "";
    display = "npm run test  # mocha --require test/support/env --reporter spec --bail --check-leaks test/ test/acceptance/";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "nodejs-test-npmscripts-test-tap-package-json" = let
    cmd = "npm run test-tap";
    requiredExec = "npm";
    workdir = "";
    display = "npm run test-tap  # mocha --require test/support/env --reporter tap --check-leaks test/ test/acceptance/";
  in pkgs.runCommand "check-nodejs-test-npmscripts-test-tap-package-json" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

}
