# Generated by autonix
# Development shell configuration
{ pkgs, lib, devPackages, notices ? []
, go ? null
, python ? null, pythonAttr ? null, wantPythonAttr ? null
, node ? null, nodeAttr ? null, wantNodeAttr ? null
, rustToolchain ? null
}:

pkgs.mkShell {
  packages = devPackages;

  shellHook = ''
    echo "autonix: generated devShell (best-effort)"

    ${lib.optionalString (go != null) ''
      echo "autonix: Go toolchain enabled (go-overlay)"
    ''}

    ${lib.optionalString (python != null) ''
      echo "autonix: Python attr: ${pythonAttr} (requested ${wantPythonAttr})"
      if [ "${pythonAttr}" != "${wantPythonAttr}" ]; then
        echo "autonix: NOTE: ${wantPythonAttr} not found; using ${pythonAttr}"
      fi
    ''}

    ${lib.optionalString (node != null) ''
      echo "autonix: Node attr: ${nodeAttr} (requested ${wantNodeAttr})"
      if [ "${nodeAttr}" != "${wantNodeAttr}" ]; then
        echo "autonix: NOTE: ${wantNodeAttr} not found; using ${nodeAttr}"
      fi
    ''}

    ${lib.optionalString (rustToolchain != null) ''
      echo "autonix: Rust toolchain enabled (rust-overlay)"
    ''}

    ${lib.concatMapStringsSep "\n" (msg: "echo ${lib.escapeShellArg msg}") notices}
  '';
}
