# Generated by autonix
#
# This flake uses a multi-file structure:
#   devShell.nix              - Development shell
#   {language}/packages.nix   - Language toolchains and tools
#   {language}/*-checks.nix   - Build and test checks
#
{
  description = "Generated by autonix (devShells.default + checks)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        lib = pkgs.lib;

        golangPackages = import ./golang/packages.nix { inherit pkgs lib; };

        genericPackages = [
          pkgs.just
        ];

        devPackages = []
          ++ genericPackages
          ++ golangPackages.packages;

        notices = []
          ++ golangPackages.notices;

        projectRoot = ./..;

      in
      {
        devShells.default = import ./devShell.nix {
          inherit pkgs lib devPackages notices;
          go = golangPackages.go or null;
          goAttr = golangPackages.goAttr or null;
          wantGoAttr = golangPackages.wantGoAttr or null;
        };

        checks = {}
          // (import ./golang/test-checks.nix { inherit pkgs lib devPackages projectRoot; })
          // (import ./golang/build-checks.nix { inherit pkgs lib devPackages projectRoot; })
          ;
      });
}
