# Generated by autonix
# Go toolchain and development tools
{ pkgs, lib }:

let
  wantGoAttr = "go";
  goAttr = if builtins.hasAttr wantGoAttr pkgs then wantGoAttr else "go";
  go = pkgs.${goAttr};

  notices = [];
in
{
  inherit go goAttr wantGoAttr notices;

  packages = [
    go
    pkgs.gopls
  ];
}
