# Generated by autonix
#
# This flake uses a multi-file structure:
#   devShell.nix              - Development shell
#   {language}/packages.nix   - Language toolchains and tools
#   {language}/*-checks.nix   - Build and test checks
#
{
  description = "Generated by autonix (devShells.default + checks)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        lib = pkgs.lib;

        nodejsPackages = import ./nodejs/packages.nix { inherit pkgs lib; };

        devPackages = []
          ++ nodejsPackages.packages;

        notices = []
          ++ nodejsPackages.notices;

        projectRoot = ./..;

      in
      {
        devShells.default = import ./devShell.nix {
          inherit pkgs lib devPackages notices;
          node = nodejsPackages.node or null;
          nodeAttr = nodejsPackages.nodeAttr or null;
          wantNodeAttr = nodejsPackages.wantNodeAttr or null;
        };

        checks = {}
          // (import ./nodejs/test-checks.nix { inherit pkgs lib devPackages projectRoot; })
          ;
      });
}
