# Generated by autonix
#
# This flake uses a multi-file structure:
#   devShell.nix              - Development shell
#   {language}/packages.nix   - Language toolchains and tools
#   {language}/*-checks.nix   - Build and test checks
#
{
  description = "Generated by autonix (devShells.default + checks)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, rust-overlay }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [
          (import ./rust/overlay.nix { inherit rust-overlay; })
        ];
        pkgs = import nixpkgs { inherit system overlays; };
        lib = pkgs.lib;

        rustPackages = import ./rust/packages.nix { inherit pkgs lib; };

        devPackages = []
          ++ rustPackages.packages;

        notices = []
          ++ rustPackages.notices;

        projectRoot = ./..;

      in
      {
        devShells.default = import ./devShell.nix {
          inherit pkgs lib devPackages notices;
          rustToolchain = rustPackages.rustToolchain or null;
        };

        checks = {}
          // (import ./rust/test-checks.nix { inherit pkgs lib devPackages projectRoot; })
          // (import ./rust/build-checks.nix { inherit pkgs lib devPackages projectRoot; })
          ;
      });
}
