# Generated by autonix
# Go test checks
{ pkgs, lib, devPackages, projectRoot }:

{
  "golang-test-gotask-test-go-mod" = let
    cmd = "go test ./...";
    requiredExec = "go";
    workdir = ".";
    display = "go test ./...";
  in pkgs.runCommand "check-golang-test-gotask-test-go-mod" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-test-make-test-makefile" = let
    cmd = "make test";
    requiredExec = "make";
    workdir = ".";
    display = "make test";
  in pkgs.runCommand "check-golang-test-make-test-makefile" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

}
