# Generated by autonix
# Go build checks
{ pkgs, lib, devPackages, projectRoot }:

{
  "golang-build-gotask-build-go-mod" = let
    cmd = "go build";
    requiredExec = "go";
    workdir = ".";
    display = "go build";
  in pkgs.runCommand "check-golang-build-gotask-build-go-mod" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-build-make-build-image-dirty-makefile" = let
    cmd = "make build-image-dirty";
    requiredExec = "make";
    workdir = ".";
    display = "make build-image-dirty";
  in pkgs.runCommand "check-golang-build-make-build-image-dirty-makefile" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-build-make-build-image-dirty-makefile-2" = let
    cmd = "make build-image-dirty";
    requiredExec = "make";
    workdir = ".";
    display = "make build-image-dirty";
  in pkgs.runCommand "check-golang-build-make-build-image-dirty-makefile-2" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-build-make-build-image-dirty-makefile-3" = let
    cmd = "make build-image-dirty";
    requiredExec = "make";
    workdir = ".";
    display = "make build-image-dirty";
  in pkgs.runCommand "check-golang-build-make-build-image-dirty-makefile-3" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-build-make-build-image-makefile" = let
    cmd = "make build-image";
    requiredExec = "make";
    workdir = ".";
    display = "make build-image";
  in pkgs.runCommand "check-golang-build-make-build-image-makefile" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-build-make-build-image-makefile-2" = let
    cmd = "make build-image";
    requiredExec = "make";
    workdir = ".";
    display = "make build-image";
  in pkgs.runCommand "check-golang-build-make-build-image-makefile-2" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-build-make-build-image-makefile-3" = let
    cmd = "make build-image";
    requiredExec = "make";
    workdir = ".";
    display = "make build-image";
  in pkgs.runCommand "check-golang-build-make-build-image-makefile-3" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-build-make-build-webui-image-makefile" = let
    cmd = "make build-webui-image";
    requiredExec = "make";
    workdir = ".";
    display = "make build-webui-image";
  in pkgs.runCommand "check-golang-build-make-build-webui-image-makefile" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-build-make-dist-makefile" = let
    cmd = "make dist";
    requiredExec = "make";
    workdir = ".";
    display = "make dist";
  in pkgs.runCommand "check-golang-build-make-dist-makefile" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

  "golang-build-make-release-packages-makefile" = let
    cmd = "make release-packages";
    requiredExec = "make";
    workdir = ".";
    display = "make release-packages";
  in pkgs.runCommand "check-golang-build-make-release-packages-makefile" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

}
