# Generated by autonix
# Go toolchain and development tools
{ pkgs, lib }:

let
  wantGoVersion = "1.23";
  go =
    if builtins.hasAttr wantGoVersion pkgs.go-bin
    then pkgs.go-bin.${wantGoVersion}
    else pkgs.go-bin.stable;

  notices = [
    "Go: requested 1.23.0 (from GoModDirective) -> want 1.23 (go-overlay provides major.minor; patch may differ)"
  ];
in
{
  inherit go notices;

  packages = [
    go
    pkgs.gopls
  ];
}
