# Generated by autonix
# Go toolchain and development tools
{ pkgs, lib }:

let
  wantGoAttr = "go_1_23";
  goAttr = if builtins.hasAttr wantGoAttr pkgs then wantGoAttr else "go";
  go = pkgs.${goAttr};

  notices = [
    "Go: requested 1.23.0 (from GoModDirective) -> want go_1_23 note: nixpkgs provides Go by major/minor (patch may differ)"
  ];
in
{
  inherit go goAttr wantGoAttr notices;

  packages = [
    go
    pkgs.gopls
  ];
}
