# Generated by autonix
# Python toolchain and development tools
{ pkgs, lib }:

let
  wantPythonAttr = "python39";
  pythonAttr = if builtins.hasAttr wantPythonAttr pkgs then wantPythonAttr else "python3";
  python = pkgs.${pythonAttr};
  wantPythonPackagesAttr = "${pythonAttr}Packages";
  pythonPackages = if builtins.hasAttr wantPythonPackagesAttr pkgs then pkgs.${wantPythonPackagesAttr} else pkgs.python3Packages;

  tox = if builtins.hasAttr "tox" pythonPackages then pythonPackages.tox else null;
  pyright = if builtins.hasAttr "pyright" pkgs then pkgs.pyright
    else if builtins.hasAttr "pyright" pkgs.nodePackages then pkgs.nodePackages.pyright
    else null;

  notices = [
    "Python: requested >=3.9 (from PyprojectRequiresPython) -> want python39 note: nixpkgs provides Python by major/minor (patch may differ)"
  ];
in
{
  inherit python pythonPackages pythonAttr wantPythonAttr notices;

  packages = [ python ]
    ++ lib.optional (tox != null) tox
    ++ lib.optional (pyright != null) pyright;
}
