# Generated by autonix
# Python test checks
{ pkgs, lib, devPackages, projectRoot }:

{
  "python-test-tox-default-tox-ini" = let
    cmd = "tox";
    requiredExec = "tox";
    workdir = ".";
    display = "tox";
  in pkgs.runCommand "check-python-test-tox-default-tox-ini" {
    nativeBuildInputs = devPackages;
  } ''
    set -euo pipefail
    export HOME="$TMPDIR/home"
    mkdir -p "$HOME"

    echo "autonix: running ${display}"
    if ! command -v "${requiredExec}" >/dev/null 2>&1; then
      echo "autonix: missing required executable in PATH: ${requiredExec}" >&2
      exit 1
    fi

    cp -r ${projectRoot} source
    chmod -R u+w source
    cd "source/${workdir}"

    ${pkgs.bash}/bin/bash -lc ${lib.escapeShellArg cmd}

    mkdir -p $out
    echo ok > $out/result
  '';

}
